.github/workflows/gh-pages.yml
---
🤶🌅Merry Christmas and Happy New Year!  
オフラインでもAmeba Accessibility Guidelineが読めるように、試験的にwebbundleを作成するようにしてみました。
例えば・・・
- 通勤時、地下鉄で電波の悪い場所がある時
- 実家に帰って、お風呂で読みたい時 (実家の電波がよくない)
- 海外旅行の飛行機で読みたい時
- 地元の友だちにガイドラインを渡したい時
などに役立ちます:grimacing:
生成されるリリースのサンプルは[Forkしたリポジトリでテスト](https://github.com/herablog/a11y-guidelines/releases/tag/webbundle-20191213105558)しました。
しばらくは `publish-webbundle` ブランチを切って手動でパブリッシュ予定です。
=> [experimental] ci: 📦 create workflow to publish guideline as web bundle

.github/auto_assign.yml, .github/workflows/auto-assign-to-renovate.yml, .renovaterc.json
---
close #30 
renovateのPRに自動で2人assignするGitHub Actionを追加しました。
PRが生成されたとき`renovate/*`という名前のブランチだった場合に https://github.com/kentaro-m/auto-assign-action を実行するというシンプルなものです。とりあえず2人指定するようにしています。
=> renovateのPRに自動でassignする

config.yml, layouts/_default/single.html
---
ビルド時の言語が`EN`になっていたので、デフォルトの言語を日本語`ja`で指定し、HTMLのlang属性の値として利用するように変更しました。生成されるファイルに変更はありません。
ビルド時の言語が`JA`になっている。
生成されたHTMLのlang属性の値が、`ja`である。
=> refactor: set default language

layouts/shortcodes/figure.html, layouts/shortcodes/video.html
---
ref: https://github.com/openameba/a11y-guidelines/pull/35#issuecomment-571933350
```
$ docker-compose run --rm serve
Building sites … WARN 2020/01/08 07:54:14 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Built in 401 ms
Error: Error building site: "/var/www/a11y-guidelines/content/2/2/2.md:35:1": failed to render shortcode "figurelist": failed to process shortcode: "/var/www/a11y-guidelines/layouts/shortcodes/figure.html:15:14": execute of template failed: template: shortcodes/figure.html:15:14: executing "shortcodes/figure.html" at <.Get>: error calling Get: reflect: call of reflect.Value.Interface on zero Value
``` …
=> fix: figure, video shortcodeのcaption条件分岐を修正

.github/workflows/build-deploy.yml
---
peaceiris/actions-gh-pages@v2 では `forceOrphan` が指定でき、これにより常にgh-pagesブランチのコミットを1つだけにできるようだったので指定してみました。
これまでwerckerでデプロイ-paしていたときと同じ挙動になるかと思います。
gh-pagesブランチがそんなにコミット増えても嬉しくないのでこちらの方が良いかなあと。
=> add forceOrphan option to actions-gh-pages

layouts/partials/meta.html
---
Twitterでシェアしたときに見切れてしまっていたので、大きな画像で見えるようにしました。
=> feat: twitter card larger

src/styles/detail/details.css
---
chromeで閲覧していた際、outlineのレイアウトが欠落していたが気になって修正したのですがどうでしょうか。
`outline-offset` なのでブラウザによって多少解釈が違ったりもしますが枠のエリアを少し変更したので問題ないかと。
あとついでに修正したcssの改行が統一されていなさそうだったので合わせて修正しました。
=> fix: summaryのoutlineを調整

package.json
`renovate` にアサインされるメンバーを一部除外しました。
必要でしたら追加できそうなメンバーを検討したい所存です。
=> fix: remove renovate assignees member

package.json
---
renovateに`group:postcss`を追加しました。これにより #122 #105 のような、一緒にアップデートされた方が嬉しいモジュールのPull-requestが作られるような気がします。
=> chore: add postcss group to renovate

npm_scripts/scrape.js
---
https://github.com/openameba/a11y-guidelines/pull/142#issuecomment-747291841 で発生しましたが、動画が存在するページでthrobberが映り込んでしまって毎回diffが出てしまう、というのを修正しました。
videoのタグがページに存在する場合は数百ミリ秒待つことにしました。 `preload="none"` や `metadata` でも試してみましたが、くるくるが写ってしまうようでした。
お手元で試す場合は以下のようにするとスクリーンショットが取得できるかと思います。
```console
$ npm install -D puppeteer
$ node ./npm_scripts/scrape.js "${PWD}/.reg-suit/actual_images" http://localhost:1313 /a11y-guidelines/2/2/2/index.html
```
=> 比較画像にthrobberが映らないようにした

.github/workflows/regression-test.yml
---
regression-testワークフローでは動作環境としてubuntu-latestを指定していますが、最近Ubuntuのバージョンがアップグレードされ、その影響により日本語フォントが入らなくなってしまったようです。なのでスクリーンショットを取得すると文字が豆腐になっていました。
豆腐のままでは困るのでワークフローの最初で日本語フォントをインストールするようにしました。フォントは名前の由来にぴったりなnotoフォントにしました。
https://storage.googleapis.com/a11y-guidelines/06b21deeebf22d92d206672569686c83375d5808/index.html?stat=q1ZKS8zMSU3xLEnNLXbOL80rUbIyNdVRykstRxYy0FFKSc1JLUFVCBQtSCwuRhOsBQA%3D
=> スクリーンショットのフォントが豆腐になってしまうのを修正

src/_includes/partials/header.njk, src/styles/common/header.css
https://github.com/openameba/a11y-guidelines/issues/151
上記issueの対応を行いました。
=> Amebaロゴに対してwidthとheightの指定を付与

.github/workflows/build-deploy.yml
---
カスタムドメイン設定に必要なCNAMEファイルを、GitHub Pagesデプロイ時に生成するようにしました。毎回masterブランチからビルドされた`public`以下がgh-pagesブランチに反映されるため都度生成しています。
https://github.com/openameba/a11y-guidelines/blob/b8c429bddcaa9638e9d1d004dbec11d1d3b08906/.github/workflows/build-deploy.yml#L22-L28
=> fix: create CNAME file to public root

.github/workflows/publish-webbundle.yml
---
Web Bundleを生成するスクリプトの中で、[廃止されたadd-pathコマンド](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)が使われていましたので、GitHubのドキュメント「[Adding a system path](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)」を参考に置き換えました。
変更前に失敗したタスク: https://github.com/openameba/a11y-guidelines/runs/2189213933?check_suite_focus=true
変更して成功したタスク: https://github.com/openameba/a11y-guidelines/runs/2189257413?check_suite_focus=true
=> chore: replace add-path

src/1/4/10.md, src/2/4/10.md, src/2/5/3.md, src/3/3/3.md, src/4/1/3.md
dark modeのチェック時に一部マークダウンへのHTML指定がなかった箇所があったため修正いたしました。
https://github.com/openameba/a11y-guidelines/issues/202
=> コードブロックにHTML指定を追加

src/1/1/1.md, src/styles/detail/details.css
[1.1.1 アイコンの実装例の再考](https://github.com/openameba/a11y-guidelines/issues/56)
の文脈から再考してみました。
issueにある言い回しからは少し変えている部分もあります。
> ただしWebに限った話であること、長くなりすぎることから、推奨例以外はaccordionなどで隠しても良いかもと思っています。
あたりがポイントでしょうか。
場合によって
- roleをimgにした上で、ラベルを設定する方法
- 親要素にラベルを設定する方法
あたりは隠してしまってもいいかもしれません。
その辺りご意見いただければ幸いです。
=> 項目1.1.1の実装例を再考

src/1/1/1.md
**1.1.1 画像に代替テキストを提供する** にアプリの実装方法を追加しました。
その影響で
- Web
- Android
- iOS
という見出しを追加し、それに紐づく見出したちは見出しレベルを1つさげています。
その影響で h6 を使用するケースが出てきたのですが文字少し小さい気もしています。
一応、修正後のスクリーンショットを載せておきます。長めです。
=> 項目1.1.1にアプリの実装方法を追加

src/styles/common/base.css
#271 の続き。
- `scroll-padding-top` でページ内スクロール時に余白をつくる
=> ページ内リンクでの遷移時に上部に余白をあける

src/_includes/partials/meta.html, src/_includes/partials/meta.njk
---
すっかり入れ忘れていた `color-scheme` の指定を入れました。
参考: https://webkit.org/blog/8840/dark-mode-support-in-webkit/
現状表示されている要素だとおそらくほぼ影響はないと思われますが、今後のためにも入れておきたいと思いますです。
=> chore: add color-scheme for dark theme

src/styles/default/heading.css, src/styles/detail/heading.css
項目1.1.1などでh5やh6の見出しが使われているのですがサイズが少し小さく見づらいというご意見があり `font-size` の指定を追加してみました。
必要最低限として `font-size` のみ追加していますが
- `h4` などと同様にline-heightやmargin指定も追加するべきか
- default.cssで使用している[heading指定](https://github.com/openameba/a11y-guidelines/blob/master/src/styles/default/heading.css)へもh6の記述追加するべきか
あたり迷ったのでもし最適解ありましたらコメントいただければと思います。
修正したことにより文字サイズ12px相当になりました。
=> 見出しに対してfont-sizeの指定を追加

src/2/3/3.md
参考文献のリンクが404だったので修正しました。
新しく設定したリンク先のタイトルは変わってなかったのでURLのみ差し替えています。
issueにあったURLのハッシュなくても問題なく遷移していそうだっためハッシュはつけておりません。
fix https://github.com/openameba/a11y-guidelines/issues/288
=> 参考文献にある404リンクを差し替え

src/1/3/2.md, src/1/3/3.md, src/2/1/2.md, src/2/2/4.md, src/4/1/2.md
表題の通り、WCAG2.0へのリンクを2.1に変更しました。
[以前](https://github.com/openameba/a11y-guidelines/pull/252)も差し替えをおこないましたが翻訳されていた箇所増えてたので追加で修正をしました。
https://github.com/openameba/a11y-guidelines/blob/master/src/1/3/2.md
想定されるWCAG2.1へのリンク（[F32](https://waic.jp/docs/WCAG21/Techniques/failures/F32)）
https://github.com/openameba/a11y-guidelines/blob/master/src/1/3/3.md
想定されるWCAG2.1へのリンク（[F14](https://waic.jp/docs/WCAG21/Techniques/failures/F14)）
https://github.com/openameba/a11y-guidelines/blob/master/src/2/1/2.md
想定されるWCAG2.1へのリンク（[F10](https://waic.jp/docs/WCAG21/Techniques/failures/F10)）
https://github.com/openameba/a11y-guidelines/blob/master/src/2/2/4.md
想定されるWCAG2.1へのリンク（[F40](https://waic.jp/docs/WCAG21/Techniques/failures/F40)）
https://github.com/openameba/a11y-guidelines/blob/master/src/4/1/2.md …
=> 達成方法集のリンクをWCAG2.1に修正

src/1/4/4.md, src/3/2/1.md
[こちらのIssue](https://github.com/openameba/a11y-guidelines/issues/253)の対応になります。
WCAG2.0解説書にリンクしていた項目を2.1に変更しました。
| G179のリンク修正 | G201のリンク修正 |
|:---:|:---:|
| ![1 4 4](https://user-images.githubusercontent.com/3806115/172542976-70c066a3-02f0-45ea-ae46-cd33b95c40ba.gif) | ![3 2 1](https://user-images.githubusercontent.com/3806115/172543050-dec0c798-ac79-44bf-a11d-d2cc58ae35a0.gif) |
=> 各項目の参考リンクがWCAG2.0解説書なので2.1に差し替える

src/2/4/7.md
---
[2.4.7 良い実装例](https://a11y-guidelines.ameba.design/2/4/7/#%E8%89%AF%E3%81%84%E5%AE%9F%E8%A3%85%E4%BE%8B)の記述を修正しました 🚀 
2.4.7の実装例としては「フォーカス時の」実装例が載っているべきでしたが、実際は「通常時の」スタイルが載っており、このコードのまま実装すると常にフォーカスが表示されてしまっています
実装例のコードのまま実装した結果👇
そのため、実装例に`:focus-visible`を追加しました
fix https://github.com/openameba/a11y-guidelines/issues/333
=> `2.4.7`の良い実装例の記述を修正

src/3/3/2.md
達成基準3.3.2の図の位置を`実装方法`から`概要`に移動しました
| before | after |
| -- | -- |
| ![スクリーンショット 2022-07-10 22 08 02](https://user-images.githubusercontent.com/42470015/178146551-c7c4636b-145b-4dca-9a78-554129b99ccb.png) | ![スクリーンショット 2022-07-10 22 17 35](https://user-images.githubusercontent.com/42470015/178146557-d1b22940-e860-453d-a653-e02fd22d3271.png) |
上記の図はあくまで概要に記載されている内容の補足にあたるので、`概要`の中に移動させました
他の章同様、`実装方法`には具体的な実装例やコードが記載されている形に統一したいです！
https://a11y-guidelines.ameba.design/3/3/2/
どこかのタイミングで3.3.2にもWebの実装方法を記載したいです
=> 達成基準3.3.2の図の位置を`実装方法`から`概要`に移動

.github/workflows/build-deploy.yml
現在 `gh-pages` ブランチをプッシュしてウェブサイトを更新する方法をとっていますが、わざわざブランチを用意せずともデプロイすることが可能になりました：
[GitHub Pages: Custom GitHub Actions Workflows (beta) | GitHub Changelog](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/)
まだベータ版なので勇足かもしれませんが、 `gh-pages` ブランチがなくなるとスッキリすると思うので対応してみました。
- [GitHub Pages: Custom GitHub Actions Workflows (beta) | GitHub Changelog](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/)
- [GitHub Pages: Builds with GitHub Actions GA | GitHub Changelog](https://github.blog/changelog/2022-08-10-github-pages-builds-with-github-actions-ga/)
- [actions/deploy-pages](https://github.com/actions/deploy-pages)
- [actions/upload-pages-artifact: A composite action for packaging and uploading an artifact that …
=> GitHub Actions から直接ウェブサイトをデプロイする

.github/workflows/visual-regression-test.yml
`set-output` でwarningが出ておりvisual regression testが動かなくなっていたものをGITHUB_OUTPUTへの書き込みに修正してみました。
このPull requestでvisual regression testが今まで通り動いていればOK。
[GitHub Actions: Deprecating save-state and set-output commands - The GitHub Blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples)
=> VRTのキャッシュ対象ディレクトリをGITHUB_OUTPUTに変更

src/2/1/1.md
issueへの起票を受けまして達成基準2.1.1の内容を修正してみました。
一部、文章表現もうちょっとわかりやすくできそうだなと思いまして
> フォーカスを受け取れない要素にクリックイベントを実装している。
フォーカスを受け取ることができない要素にクリックイベントを実装している。
> 要素を変更できない場合などに、tabindex属性を付与してフォーカス可能にすることもできる。ただしこの場合、別項2.4.7 フォーカスを見えるようにするにも留意する。
フォーカス可能な要素に変更できない場合、tabindex属性を付与してフォーカス可能にできる。ただしこの場合、別項2.4.7 フォーカスを見えるようにするにも留意する。
https://github.com/openameba/a11y-guidelines/issues/258
=> 達成基準2.1.1の内容を修正

src/2/1/2.md
詳細は[2.1.2のキーボード操作の良い実装例を、Event.keyCode→Event.keyに修正する](https://github.com/openameba/a11y-guidelines/issues/387)のissueを見ていただければと思うのですが `keyCode` は非推奨なので `key` に修正しました。
https://github.com/openameba/a11y-guidelines/issues/387
=> 達成基準2.1.2の実装例を修正

.husky/pre-commit, package.json
[npm 9で `npm bin` が廃止になり](https://github.com/npm/cli/blob/v9.8.1/CHANGELOG.md#-breaking-changes)、localでlint-stagedの実行に失敗してコミットできなくなっていたので修正しました。
node 18に上がってからも他の人コミットしていそうだしターミナルでやるとダメとかあるんでしょうか 🤔 
1. npm 9以上（node 18ならなると思うが・・）でmasterブランチをcheckout
2. 何かのファイルを適当に修正する
3. git commitする
4. 失敗することを確認
5. このブランチをcheckoutする
6. 何かのファイルを適当に修正する
7. git commitする
8. 成功することを確認
近そうなPRとコメント
https://github.com/openameba/a11y-guidelines/pull/197#pullrequestreview-624194351
=> fix: npm9でコミットできない

.github/workflows/build-deploy.yml, .github/workflows/publish-webbundle.yml, .github/workflows/test.yml
https://github.com/openameba/a11y-guidelines/pull/363 で（＋それ以降のminorアップデートでも）18になっていたもののworkflowの方は16のままになっていたので修正しました。
手元では18で確認していたのでまぁ大丈夫でしょう・・:pray:
→package.jsonから取得できるとのことなので修正 🙌 
- CIが通るのを見守る
- マージ後deployされたやつがおかしなことにならないことを祈る
=> chore: GitHub Workflowのnodeバージョン指定をpackage.jsonから取得する

src/styles/detail/details.css
折りたたみ表示のsummary要素の先頭文字が見切れているのを修正しました。
before|after
---|---
先頭文字が見切れている|先頭文字が全て見えている
https://github.com/openameba/a11y-guidelines/pull/417#discussion_r1354137631
=> fix: summary要素の先頭文字が見切れている

.github/workflows/publish-webbundle.yml
- ２年ぶりくらいにwebbundle作ろうとしたら[コケてしまった](https://github.com/openameba/a11y-guidelines/actions/runs/6491084777/job/17627852833#step:5:1)
- [GoはたしかHugoのために入れていたはず](https://github.com/openameba/a11y-guidelines/pull/29/files#diff-c04119feaeffc2c216f069aec66797f2f839a2074287060698e3a2440dec8d45R39-R45)なので、今は不要なはず
- Go installを削除
=> chore: fix publish-webbundle

src/2/4/3.md
https://openameba.github.io/a11y-guidelines/2/4/3/ に
https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html#navigation-mechanisms-focus-order-examples-head の事例を追加しました。
fix:  #9 
=> feat: dialog起動時のフォーカス順序の事例を導入

src/1/4/3.md
[1.4.3 テキストや文字画像のコントラストを確保する](https://a11y-guidelines.ameba.design/1/4/3/)の「大きな文字」の基準が英語のサイズから、日本語の全角文字基準のサイズに変更しました。
fix: #433 
=> fix: 「大きな文字」の基準を日本語の全角文字基準に

package-lock.json, package.json
Reverts openameba/a11y-guidelines#465
=> Revert "chore(deps): update dependency markdown-it-anchor to v9"

package.json
src配下以外の `*.md` ファイル（ `CONTRIBUTING.md` など）には 「ですます」口調があるため、当該ファイルを変更後にcommitしようとすると、textlintのエラーが発生します。
textlintは公開面の `*.md` ファイルに適用できれば良いので、 lint-stagedのtextlintのターゲットファイルを `*.md`から`src/*.md`に変更します。
試しに `CONTRIBUTING.md` に差分を作って commit & pushしてCIがパスすることを確認しました✅
- #477 
- このPRの内容をcommitしたらtextlintエラーになったため、修正しました
=> fix: lint-stagedのtextlintのターゲットをsrc/*.mdに変更

CONTRIBUTING.md
https://github.com/openameba/a11y-guidelines/pull/147 で11tyに変更になった際にローカル環境のURLが変わりましたが、`CONTRIBUTING.md` の更新が漏れていたため修正します。
- https://github.com/openameba/a11y-guidelines/pull/147
=> docs: ローカル開発のURLを修正

.renovaterc.json, package.json
https://docs.renovatebot.com/configuration-options/#configuration-options によると package.json の renovate 設定は将来的に削除する予定とのことなので設定を .renovaterc.json に分離しました。
なし
https://github.com/openameba/spindle/blob/main/.renovaterc.json の設定に似せました。
=> chore: split renovate config to file

src/1/4/3.md
以下セクションのtota11yのリンクが切れていたので該当文章を削除しました。
[実装時](https://a11y-guidelines.ameba.design/1/4/3/#%E5%AE%9F%E8%A3%85%E6%99%82)
#487 
=> fix: [1.4.3] リンク切れしているtota11yの文章を削除

.github/workflows/test.yml
actions/cache@v3の廃止に伴い、1月末までにv4への更新が必要です
setup-nodeのcacheオプションは内部でactions/cache@v3が利用されているため、これをやめて自前でactions/cacheを使います（setup-node側の更新待ちとなり、期限内に柔軟な対応が出来ないため）
https://www.notion.so/cyberagent-group/openameba-a11y-guidelines-165b68753fe980209f05f61ec35853f0
https://github.com/actions/toolkit/discussions/1890
lighthouseのtestワークフローが正常終了していればOKです
1月中にマージ
=> ci: actions/cacheをv4に更新
