openameba/a11y-guidelines

- layouts/partials/meta.html
---
現在は使われていない、base要素を削除しました。
close #2
> refactor: remove unused base element

- .github/workflows/test.yml
- README.md
- package-lock.json
---
GitHub Actionsでテストを実行するようにしました。
完全には移行できていないため `.circleci` は削除していません。 ref: #16
> add test workflow

- .renovaterc.json
- README.md
> add renovate

- wercker.yml
---
公開時でもHTMLが圧縮されていなかったと思ったので、パラメータに`--minify`をつけるようにしました。
https://github.com/ArjenSchwarz/wercker-step-hugo-build
たぶんこれだと思うので、指定の仕方はあってると思うんですが……
> minify HTML

- .github/workflows/test.yml
- .lighthouserc.json
- package-lock.json
---
push / pull-request のたびにLighthouse CIとhugo buildのテストがされるようにしました。
#15 があるので `/2/2/2` はLighthouseのテストに含めませんでした。
- ref #15 
- close #16
> add Lighthouse CI

- content/_index.md
---
fix: https://github.com/openameba/a11y-guidelines/issues/74
> fix: 1.3.5の適合レベルの修正

- content/_index.md
- layouts/partials/footer.html
- layouts/partials/meta.html
---
Ameba Accessibility GuidelinesのページにGAの計測タグを追加しました。
> Google Analyticsのタグを追加

- layouts/partials/meta.html
---
OGPの画像パスが間違ったいました。
ローカルでの挙動と本番環境での挙動が若干違う気が。
> OGPへの参照パスを修正

- LICENSE.md
- package.json
---
resolve https://github.com/openameba/a11y-guidelines/issues/99 
ガイドライン本文とガイドラインをビルドするためのプログラム、またAmebaのブランドアセットごとにライセンスを分けて定義した。
> fix: license

- LICENSE.md
---
MITライセンス使用において記載漏れがあったので、著作権発生年と著作権保持者、ライセンス本文を追加。ついでにリンクも追加。
> feat: add license text and link

- package.json
---
renovateが作ってくれるPRのassigneesに勝手に追加しました:pray:
> add renovate assignees

- layouts/partials/header.html
- src/styles/common/base.css
- src/styles/common/color.css
- src/styles/common/figure.css
- src/styles/common/footer.css
- src/styles/common/header.css
- src/styles/common/index.css
- src/styles/common/label.css
- src/styles/common/license.css
- src/styles/common/overrides.css
- src/styles/common/rule_label.css
- src/styles/default/heading.css
- src/styles/detail/code.css
- src/styles/detail/details.css
- src/styles/detail/heading.css
---
- ameba color palette v3 の利用 => resolve #15
- font-family あたりを Spindle の規定に変更
- その他リファクタリング
- font-size を大きく（タイプフェイスが変更されたため）
- `html { font-size: 62.5% }` を駆逐
- font-size 依存でなくてもよい余白を px に変更
- 文字サイズをすべて rem に
- focus スタイルの変更
|before|after|
|----|----|
|![openameba github io_a11y-guidelines_(iPad Pro)](https://user-images.githubusercontent.com/6724665/97433340-af16e480-1960-11eb-9954-ecf5b4bc0b67.png)|![localhost_1313_a11y-guidelines_(iPad Pro)](https://user-images.githubusercontent.com/6724665/97433364-bb02a680-1960-11eb-85b8-12e6027e5a00.png)|
|before|after|
|----|----|
|![openameba github io_a11y-guidelines_1_1_1_(iPad Pro)](https://user-images.githubusercontent.com/6724665/97433521-ff8e4200-1960-11eb-9db7-7bd75bec231b.png)|![localhost_1313_a11y-guidelines_1_1_1_(iPad …
> Spindle のスタイルを使用する

- .github/workflows/build-deploy.yml
---
master の deploy error 修正（peaceiris/actions-gh-pages@v3 への対応）
> fix: deploy actions

- .github/workflows/regression-test.yml
- .gitignore
- npm_scripts/scrape.js
- regconfig.json
---
reg-suitによるテストを入れました。[openameba/spindle](https://github.com/openameba/spindle/pull/89#issuecomment-722875987) で使っているようにデザインが崩れたらどのあたりが崩れたのかすぐにわかるので便利かと思います。
ちなみにHugoのバージョンを上げたらliのあたりが崩れたので、これを入れて確認しつつ直したいなと思った次第です。
> reg-suitで回帰テストをする

- content/1/4/4.md
---
1.4.4 の実装例の改修
- 良い実装例から root element のフォントサイズ調整を削除
- 悪い実装例についてWCAG2.1（2.1）においては必ずしも不適合にならないことを説明 related #90
> refactor: 1.4.4 text size example

- src/_includes/404.njk
- src/_includes/index.njk
- src/_includes/single.njk
11tyに移行したタイミングっぽいのですがlangの言語指定がうまく参照できていなさそうだったため修正しました。
> lang属性の処理を修正

- src/_includes/partials/footer.njk
表題の通りです。
軽微な修正のためマージしてしまおうと思います。
> 画像に幅と高さを指定

- .firebaserc
- .github/workflows/deploy-preview.yml
- firebase.json
---
プルリクエスト毎に生成結果をプレビューできるようにしました。#187 でURLの指定も相対的にしているので、どこの環境でもホスティングできると思います。
ドメインも当たりまして #148 、Amebaデザインシステムの関連ということで、そちらで使っているFirebaseと共有することにしました。サイト設定、環境変数設定は済んでいるので、正常に動くと思われます・・！
resolve #127
> chore: deploy preview for every PR

- package.json
---
lint-stagedの設定が簡略化できそうだったので簡略化しました。
`*.md`, `*.css`, `*.js`, `package.json` をそれぞれlintで引っかかるような記述をした上でgit commitしてコミットできずにエラーになるかどうかを試してみてほしいです。
> simplify lint-staged settings

- package.json
---
固有のnpmバージョンを使う意図はなさそうなので、nodeバージョンごとのnpmを使うように変更しました。
ref: https://github.com/openameba/a11y-guidelines/pull/218#issuecomment-842865996
close #218
> chore: remove unnecessary npm version

- .github/workflows/deploy-preview.yml
---
Pull Request毎にプレビューを作成していますが、30日も保持する必要がなさそうなので、ストレージ容量削減のためにも7日にしてみました。
7日以内に**すぐ**マージしましょう！w (再度pushすれば期間が更新されます)
> ci: set expires 7d for site preview

- .github/workflows/deploy-preview.yml
---
Pull Request毎にプレビューを作るためのファイルを指定し、必要のない変更でプレビューが作成されないようにしました。
関連: https://github.com/openameba/a11y-guidelines/pull/246#issuecomment-924761941
> ci: specify files to deploy preview

- .github/workflows/regression-test.yml
- .github/workflows/test.yml
- `actoins/cache` を使わずに `actions/setup-node` にキャッシュの管理を任せるようにしました
- `test` ワークフローが二重に起動していたのを抑止しました
- `regression test` ワークフローもやろうかと思ったんですが、とりあえずソノママ
> ワークフローを省電力化した

- src/1/3/1.md
**1.3.1 情報や関係性を明確にする** にアプリの実装方法を追加しました。
☝️修正後のスクリーンショットです。
> 項目1.3.1にアプリの実装方法を追加

- src/404.md
- src/robots.txt.njk
- src/sitemap.xml.njk
`sitemap.xml` を追加（`robots.txt`も）しました。検索により引っ掛かりやすくなるかな〜と思っているのですが、いかがでしょう？
ref: https://11ty.recipes/recipes/add-a-sitemap/
> sitemap.xmlを追加

- src/1/3/2.md
**1.3.2 意味のある順序でコンテンツを表現する** にアプリの実装方法を追加しました。
> 項目1.3.2にアプリの実装方法を追加

- src/2/1/1.md
**2.1.1 キーボード、タッチデバイスで操作できる** にアプリの実装方法を追加しました。
> 項目2.1.1にアプリの実装方法を追加

- src/2/1/2.md
**2.1.2 キーボード操作を可能にする** にアプリの実装方法を追加しました。
> 項目2.1.2にアプリの実装方法を追加

- src/2/4/3.md
**2.4.3 適切なフォーカス順序にする** にアプリの実装方法を追加しました。
> 項目2.4.3にアプリの実装方法を追加

- src/3/1/1.md
**3.1.1 ページの言語を指定する** にアプリの実装方法を追加しました。
iosの部分は加筆したかったのですがたたきからだといまいち記載するイメージが湧かず何かよい伝え方あったらご指摘いただけると嬉しいです。
> 項目3.1.1にアプリの実装方法を追加

- src/3/3/2.md
**3.3.2 入力項目にラベルまたは説明をつける** にアプリの実装方法を追加しました。
> 項目3.3.2にAndroidの実装方法を追加

- .github/workflows/deploy-preview.yml
---
依存パッケージの更新 (e.g.  #322) でもPreviewサイトができあがるようにしました、こりでローカルで確認しなくてもできるようになるはずです。
これがmasterブランチに取り込まれた後に各PRの「If you want to rebase/retry this PR, click this checkbox.」にチェックを入れると反映されます。
> Deploy preview site on deps updates

- .github/workflows/visual-regression-test.yml
VRT のワークフローが実行される条件を少し変更しました。
特になし
- textlintを実行しエラーが出ていないか
- Accessibility
- altは適切に設定したか([参考(1.1.1 画像に代替テキストを提供する)](https://openameba.github.io/a11y-guidelines/1/1/1/))
特になし
> VRT のワークフローの条件を変更した

- src/2/4/8.md
[textlint rule preset for Ameba](https://github.com/openameba/textlint-rule-preset-ameba) にかけてみたところタイトルの変更を指摘されたため修正してみました。
> 達成基準2.4.8のタイトルを変更

- src/_includes/partials/meta.html
- src/_includes/partials/meta.njk
meta（`twitter:site`）に指定されているアカウントが[Ameba Topics](https://twitter.com/ameba_official)になっていましたが、[Ameba Accessibility Team](https://twitter.com/AmebaA11Y)の方が適切な気がしたので修正しました
特になし（たまたま見つけました）
- [-] textlintを実行しエラーが出ていないか
- [-] Accessibility
- [-] altは適切に設定したか([参考(1.1.1 画像に代替テキストを提供する)](https://openameba.github.io/a11y-guidelines/1/1/1/))
> feat: update twitter account

- src/3/1/5.md
fix https://github.com/openameba/a11y-guidelines/issues/403
[3.1.5 難しい文章表現を避ける](https://a11y-guidelines.ameba.design/3/1/5)の`テスト・チェック方法`にSpindleのUIラベリングルールセクションを追加しました
[3.1.5 難しい文章表現を避けるに、SpindleのUIラベリングの紹介を掲載する](https://github.com/openameba/a11y-guidelines/issues/403)
- [-] Accessibility
- [-] altは適切に設定したか([参考(1.1.1 画像に代替テキストを提供する)](https://openameba.github.io/a11y-guidelines/1/1/1/))
9/27（水）
> 達成基準3.1.5にSpindleのUIラベリングルールセクションを追加

- .github/workflows/publish-webbundle.yml
ごめんなさいGoじゃなくてライブラリのinstall箇所でコケてたので消しちゃだめでした:joy:
ライブラリのinstall方法を修正します。
https://github.com/openameba/a11y-guidelines/pull/423
https://github.com/openameba/a11y-guidelines/actions/runs/6491084777/job/17627852833#step:5:1
> chore: fix publish-webbundle

- .github/workflows/build-deploy.yml
Reverts openameba/a11y-guidelines#440
> Revert "chore(deps): update actions/deploy-pages action to v4"

- .renovaterc.json
renovate の設定を更新しました。
特になし
- Accessibility
- altは適切に設定したか([参考(1.1.1 画像に代替テキストを提供する)](https://openameba.github.io/a11y-guidelines/1/1/1/))
特になし
> chore: migrate renovate settings

- npm_scripts/scrape.js
VRTの画像を取得するにあたり動画や画像の読み込みを待つように修正しました。
また、ページにアクセスした時に4xxや5xxだった時にコマンドを失敗とするようにしました。
- close #528
- close #529
- close #531
- close #182 
- textlintを実行しエラーが出ていないか
- Accessibility
- altは適切に設定したか([参考(1.1.1 画像に代替テキストを提供する)](https://openameba.github.io/a11y-guidelines/1/1/1/))
> chore: wait for assets loading
